Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loading `train_dataloader` to estimate number of stepping batches.
SLURM auto-requeueing enabled. Setting signal handlers.
┏━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃[1m   [22m┃[1m Name                  [22m┃[1m Type               [22m┃[1m Params [22m┃
┡━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ 0 │ pos_encoder           │ PositionalEncoding │      0 │
│ 1 │ encoder               │ Sequential         │  1.3 M │
│ 2 │ transformer_encoder   │ TransformerEncoder │  3.2 M │
│ 3 │ decoder               │ Sequential         │  329 K │
│ 4 │ dataset_num_embedding │ Embedding          │     32 │
│ 5 │ binary_decoder        │ Sequential         │  2.2 M │
│ 6 │ pe_embedding          │ Embedding          │  744 M │
└───┴───────────────────────┴────────────────────┴────────┘
[1mTrainable params[22m: 7.0 M
[1mNon-trainable params[22m: 744 M
[1mTotal params[22m: 751 M
[1mTotal estimated model params size (MB)[22m: 3.0 K
[37mEpoch 0/15[39m [38m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[39m [37m0/72[39m [38m0:00:00 • -:--:--[39m [38m0.00it/s[39m [37m 
[?25h
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/yhr/UCE_train/train_lit.py", line 169, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/yhr/UCE_train/train_lit.py", line 127, in main
[rank0]:     trainer.fit(model=model, train_dataloaders=dataloader)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 532, in fit
[rank0]:     call._call_and_handle_interrupt(
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 93, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 571, in _fit_impl
[rank0]:     self._run(model, ckpt_path=ckpt_path)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 980, in _run
[rank0]:     results = self._run_stage()
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1023, in _run_stage
[rank0]:     self.fit_loop.run()
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
[rank0]:     self.advance()
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 355, in advance
[rank0]:     self.epoch_loop.run(self._data_fetcher)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 133, in run
[rank0]:     self.advance(data_fetcher)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 190, in advance
[rank0]:     batch = next(data_fetcher)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 126, in __next__
[rank0]:     batch = super().__next__()
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 58, in __next__
[rank0]:     batch = next(self.iterator)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 285, in __next__
[rank0]:     out = next(self._iterator)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 65, in __next__
[rank0]:     out[i] = next(self.iterators[i])
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/_utils.py", line 705, in reraise
[rank0]:     raise exception
[rank0]: KeyError: Caught KeyError in DataLoader worker process 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/home/yhr/UCE_train/data.py", line 59, in __getitem__
[rank0]:     sample_cell_sentences(counts, weights, dataset, self.args,
[rank0]:   File "/home/yhr/UCE_train/data.py", line 128, in sample_cell_sentences
[rank0]:     chroms = dataset_to_chroms[dataset]
[rank0]: KeyError: '3a15ab1c-c36c-4842-9a3e-47e6ffd0ba6f'
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/yhr/UCE_train/train_lit.py", line 169, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/yhr/UCE_train/train_lit.py", line 127, in main
[rank0]:     trainer.fit(model=model, train_dataloaders=dataloader)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 532, in fit
[rank0]:     call._call_and_handle_interrupt(
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 93, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 571, in _fit_impl
[rank0]:     self._run(model, ckpt_path=ckpt_path)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 980, in _run
[rank0]:     results = self._run_stage()
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1023, in _run_stage
[rank0]:     self.fit_loop.run()
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
[rank0]:     self.advance()
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 355, in advance
[rank0]:     self.epoch_loop.run(self._data_fetcher)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 133, in run
[rank0]:     self.advance(data_fetcher)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 190, in advance
[rank0]:     batch = next(data_fetcher)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 126, in __next__
[rank0]:     batch = super().__next__()
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 58, in __next__
[rank0]:     batch = next(self.iterator)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 285, in __next__
[rank0]:     out = next(self._iterator)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 65, in __next__
[rank0]:     out[i] = next(self.iterators[i])
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/_utils.py", line 705, in reraise
[rank0]:     raise exception
[rank0]: KeyError: Caught KeyError in DataLoader worker process 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/home/yhr/.conda/envs/uce/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/home/yhr/UCE_train/data.py", line 59, in __getitem__
[rank0]:     sample_cell_sentences(counts, weights, dataset, self.args,
[rank0]:   File "/home/yhr/UCE_train/data.py", line 128, in sample_cell_sentences
[rank0]:     chroms = dataset_to_chroms[dataset]
[rank0]: KeyError: '3a15ab1c-c36c-4842-9a3e-47e6ffd0ba6f'